# AppleTV-Lint Configuration
# ---------------------------------------------------
# This file is all about keeping your Apple TV (tvOS)
# project squeaky clean and ready for the big screen!
# ---------------------------------------------------

excluded:
  # Directories or modules we don’t want to lint
  - "LegacyScreensavers"
  - "OldRemoteControllers"
  - "OutdatedAds"
  - "PrivateTrailers"
  - "ExperimentalHDR"

tv_performance_rules:
  # Keep your tvOS app running smooth
  - ensure_high_framerate      # 60fps or bust!
  - minimize_network_stalling  # Watch for blocking calls
  - optimize_media_decoding    # Efficient use of hardware decoding
  - swiftui_view_performance   # Don’t let your SwiftUI slow you down

tv_style_rules:
  # Make your Apple TV interface look amazing
  - big_screen_safe_area       # Avoid clipping near edges
  - consistent_remote_focus    # Clearly show which item is focused
  - large_text_for_distance    # Don’t make users squint
  - theme_consistency          # Keep the UI color scheme cohesive

tv_experience_rules:
  # Ensure a pleasant user experience
  - no_blocking_main_thread    # Don’t freeze the UI
  - avoid_forced_binge         # Respect user choice to stop streaming
  - default_subtitle_visibility
  - limit_modal_dialogs        # Don’t spam users with pop-ups

analyzer_rules:
  # Hypothetical advanced checks
  - detect_unused_scenes       # Scenes not linked anywhere
  - track_unused_assets        # Identify leftover images or media
  - flag_excessive_logging     # Don’t spam console logs
  - highlight_dangerous_apis   # Nudges to avoid outdated or private APIs

# “Global” thresholds for your Apple TV code
screen_line_length: 120
episode_file_length: 400

scene_body_length: 200
action_body_length: 80

view_complexity: 8

nesting:
  screen_level: 2
  menu_level: 2
  check_nesting_in_swiftui_views: true
  always_allow_one_scene_in_menus: false

identifier_name:
  allowed_symbols: ["_"]

type_contents_order:
  order:
    - tv_interface
    - tv_view_model
    - tv_controller
    - tv_assets
    - tv_navigation
    - tv_test_suite
